from dataclasses import dataclass

from models.classification.classification_model_configuration import ClassificationModelConfiguration
from models.video.video_model_configuration import VideoModelConfiguration


@dataclass
class VideoClassificationModelConfiguration(VideoModelConfiguration, ClassificationModelConfiguration):
    pass
